language: java
jdk:
  - openjdk8

script:

  - gradle test
  - echo "A continuación se muestra el contenido de la carpeta build:"
  - ls build
  - echo "A continuación se muestra el resultado de la ejecución:"
  - gradle  run
